{% set name = "umnn" %}
{% set version = "1.71" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/umnn-{{ version }}.tar.gz
  sha256: bdd41d941a5d904e2217a960a9584922afad8068304976dc6fb0245e4f834996

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=1.1
    - numpy

test:
  imports:
    - UMNN
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/AWehenkel/UMNN
  summary: Unconstrained Monotonic Neural Networks
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/AWehenkel/UMNN

extra:
  recipe-maintainers:
    - matthewfeickert
